---
- name: EPEL | Check if EPEL repo is already configured
  stat:
    path: "{{ epel_repo_file_path }}"
  register: epel_repofile_result

- name: EPEL | Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: EPEL | Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
